import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Shwetha',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: true,
      isSeller: false,
      seller: {
        name: 'Nike',
        logo: '/images/Brands/Nike.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Sonu',
      email: 'seller@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Adidas',
        logo: '/images/Brands/adidas.png',
        description: 'top seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Nike Top',
      slug: 'nike-top',
      category: 'Cloths',
      image: '/similarimg1/top4black.jpg',

      price: 300,
      countInStock: 10,
      brand: 'Nike',
      size: 'XL',
      rating: 4.5,
      numReviews: 15,
      description: 'High Quality Top',
    },
    {
      //_id: '2',
      name: 'Nike Fit Top',
      slug: 'nike-fit-top',
      category: 'Cloths',
      image: '/similarimg2/pinksweets1.jpg',

      price: 350,
      size: 'XL',
      countInStock: 10,
      brand: 'Nike',
      rating: 3.0,
      numReviews: 15,
      description: 'High Quality Top',
    },
    {
      //_id: '3',
      name: 'Adidas Top',
      slug: 'adidas-top',
      category: 'Cloths',
      image: '/similarimg3/topgreen3.png',

      price: 250,
      countInStock: 10,
      brand: 'Adidas',
      rating: 5.0,
      numReviews: 15,
      description: 'High Quality Top',
    },
    {
      //_id: '4',
      name: 'Adidas fit Top',
      slug: 'adidas-fit-top',
      category: 'Cloths',
      image: '/similarimg4/img1purpule.png',

      price: 400,
      countInStock: 10,
      brand: 'Adidas',
      rating: 2.0,
      numReviews: 15,
      description: 'High Quality Top',
    },
    {
      //_id: '5',
      name: 'Nike Pink shoe',
      slug: 'nike-pink-shoe',
      category: 'Shoes',
      image: '/images/shoes/shoes9.jpg',

      price: 500,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'High Quality Shoes',
    },
    {
      //_id: '6',
      name: 'Nike Color Light shoe',
      slug: 'nike-color-light-shoe',
      category: 'Shoes',
      image: '/images/shoes/shoes10.jpg',

      price: 800,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'High Quality Shoes',
    },
    {
      //_id: '9',
      name: 'Pink shoe',
      slug: 'Pink-shoe',
      category: 'Shoes',
      image: '/images/shoes/shoes11.jpg',

      price: 400,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 15,
      description: 'High Quality Shoes',
    },
    {
      //_id: '10',
      name: 'Red High Heel shoe',
      slug: 'red-high-heel-shoe',
      category: 'Shoes',
      image: '/images/shoes/shoes12.jpg',

      price: 500,
      countInStock: 10,
      brand: 'Puma',
      rating: 2.0,
      numReviews: 15,
      description: 'High Quality Shoes',
    },
    {
      //_id: '16',
      name: 'Alloy Rhodium Necklace',
      slug: 'alloy-rhodium-necklace',
      category: 'Jewelary',
      image: '/images/jewelary/jewelimg13.jpg',

      price: 500,
      countInStock: 10,
      brand: 'Sukkhi',
      rating: 5.0,
      numReviews: 15,
      description: 'Princess Necklace  White stone ',
    },
    {
      //_id: '17',
      name: 'Princes Crown Ring',
      slug: 'princess-crown-ring',
      category: 'Jewelary',
      image: '/images/jewelary/ringimg3.jpg',

      price: 500,
      countInStock: 10,
      brand: 'Martina',
      rating: 5.0,
      numReviews: 15,
      description: 'Princess crown ring, wedding white and silver rings',
    },
    {
      //_id: '18',
      name: 'Letter Initial Ring',
      slug: 'letter-initial-ring',
      category: 'Jewelary',
      image: '/images/jewelary/ringimg1.jpg',

      price: 500,
      countInStock: 10,
      brand: 'Martina',
      rating: 5.0,
      numReviews: 15,
      description:
        'Stylish Heart Name Alphabet Letter Initial K Ring for girls',
    },
    {
      //_id: '19',
      name: 'Gold Jhumka',
      slug: 'gold-jhumka',
      category: 'Jewelary',
      image: '/images/jewelary/jumka1.jpg',

      price: 500,
      countInStock: 10,
      brand: 'Sukkhi',
      rating: 5.0,
      numReviews: 15,
      description: 'Sukkhi Fashion Jewelary Antique Oxidised Gold Jhumka ',
    },
    {
      //_id: '20',
      name: 'Black Bluetooth Headset',
      slug: 'black-bluetooth-headset',
      category: 'Electronics',
      image: '/images/electronics/bluetoothHPimg.1.jpeg',

      price: 2000,
      countInStock: 10,
      brand: 'Boat',
      rating: 4.5,
      numReviews: 15,
      description: 'Boat Rockerz bluetooth Headset(Buoyany Black, on the Ear)',
    },
    {
      //_id: '21',
      name: 'Purple Bluetooth Headphones',
      slug: 'purple-bluetooth-headphones',
      category: 'Electronics',
      image: '/images/electronics/bluetoothHPimg6.jpg',

      price: 5100,
      countInStock: 10,
      brand: 'Boat',
      rating: 5.0,
      numReviews: 15,
      description:
        'Purpule Wireless  Headset with mic, LED Light and Headphone combines elements of music,lights,color together',
    },

    {
      //_id: '24',
      name: 'Apple iPhone 13 Pink',
      slug: 'apple-iphone-pink',
      category: 'Electronics',
      image: '/images/electronics/phoneimg2.jpg',

      price: 90000,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'Apple iPhone 13  Pink 256GB',
    },
    {
      //_id: '25',
      name: 'Apple iPhone 12 Pro Max',
      slug: 'apple-iphone-pro-max',
      category: 'Electronics',
      image: '/images/electronics/phoneimg5.jpg',

      price: 100000,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 15,
      description: 'Apple iPhone 12 Pro Max Pacific Blue 256GB',
    },
  ],
};

export default data;
